services:
  - type: web
    name: next-web
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: NEXT_PUBLIC_CREATE_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_CREATE_API_BASE_URL
        sync: false
      - key: NEXT_PUBLIC_PROJECT_GROUP_ID
        sync: false
      - key: NODE_VERSION
        value: 20.10.0
